// Generated by CoffeeScript 1.7.1
(function() {
  var odd;

  odd = function(num) {
    if (typeof num === 'number') {
      if (num === Math.round(num)) {
        if (num > 0) {
          return num % 2 === 1;
        } else {
          throw "" + num + "不是正数";
        }
      } else {
        throw "" + num + "不是整数";
      }
    } else {
      throw "" + num + "不是数字";
    }
  };

  console.log(odd(1));

  console.log(odd(2));

  console.log(odd(1.5));

  console.log(odd('tmd'));

}).call(this);
